-- DROP TABLE L_AIRLINE_ID;
CREATE TABLE L_AIRLINE_ID (
	CODE SMALLINT NULL,
	DESCRIPTION TEXT NULL)
DISTRIBUTE BY (CODE);

-- DROP TABLE L_AIRPORT;
CREATE TABLE L_AIRPORT (
	CODE CHAR(3) NULL,
	DESCRIPTION TEXT NULL)
DISTRIBUTE BY (CODE);

-- DROP TABLE L_AIRPORT_ID;
CREATE TABLE L_AIRPORT_ID (
	CODE INTEGER NULL,
	DESCRIPTION TEXT NULL)
DISTRIBUTE BY (CODE);

-- DROP TABLE L_AIRPORT_SEQ_ID;
CREATE TABLE L_AIRPORT_SEQ_ID (
	CODE INTEGER NULL,
	DESCRIPTION TEXT NULL)
DISTRIBUTE BY (CODE);

-- DROP TABLE L_CANCELATION;
CREATE TABLE L_CANCELATION (
	CODE CHAR(1) NULL,
	DESCRIPTION TEXT NULL)
DISTRIBUTE BY (CODE);

-- DROP TABLE L_CARRIER_HISTORY;
CREATE TABLE L_CARRIER_HISTORY (
	CODE CHAR(2) NULL,
	DESCRIPTION TEXT NULL)
DISTRIBUTE BY (CODE);

-- DROP TABLE L_CITY_MARKET_ID;
CREATE TABLE L_CITY_MARKET_ID (
	CODE INTEGER NULL,
	DESCRIPTION TEXT NULL)
DISTRIBUTE BY (CODE);

-- DROP TABLE L_DEPARRBLK;
CREATE TABLE L_DEPARRBLK (
	CODE CHAR(9) NULL,
	DESCRIPTION TEXT NULL)
DISTRIBUTE BY (CODE);

-- DROP TABLE L_DISTANCE_GROUP_250;
CREATE TABLE L_DISTANCE_GROUP_250 (
	CODE SMALLINT NULL,
	DESCRIPTION TEXT NULL)
DISTRIBUTE BY (CODE);

-- DROP TABLE L_MONTHS;
CREATE TABLE L_MONTHS (
	CODE SMALLINT NULL,
	DESCRIPTION TEXT NULL)
DISTRIBUTE BY (CODE);

-- DROP TABLE L_ONTIME_DELAY_GROUPS;
CREATE TABLE L_ONTIME_DELAY_GROUPS (
	CODE SMALLINT NULL,
	DESCRIPTION TEXT NULL)
DISTRIBUTE BY (CODE);

-- DROP TABLE L_QUARTERS;
CREATE TABLE L_QUARTERS (
	CODE SMALLINT NULL,
	DESCRIPTION TEXT NULL)
DISTRIBUTE BY (CODE);

-- DROP TABLE L_STATE_ABR_AVIATION;
CREATE TABLE L_STATE_ABR_AVIATION (
	CODE CHAR(2) NULL,
	DESCRIPTION TEXT NULL)
DISTRIBUTE BY (CODE);

-- DROP TABLE L_STATE_FIPS;
CREATE TABLE L_STATE_FIPS (
	CODE SMALLINT NULL,
	DESCRIPTION TEXT NULL)
DISTRIBUTE BY (CODE);

-- DROP TABLE L_UNIQUE_CARRIERS;
CREATE TABLE L_UNIQUE_CARRIERS (
	CODE CHAR(2) NULL,
	DESCRIPTION TEXT NULL)
DISTRIBUTE BY (CODE);

-- DROP TABLE L_WEEKDAYS;
CREATE TABLE L_WEEKDAYS (
	CODE SMALLINT NULL,
	DESCRIPTION TEXT NULL)
DISTRIBUTE BY (CODE);

-- DROP TABLE L_WORLD_AREA_CODES;
CREATE TABLE L_WORLD_AREA_CODES (
	CODE SMALLINT NULL,
	DESCRIPTION TEXT NULL)
DISTRIBUTE BY (CODE);

-- DROP TABLE L_YESNO_RESP;
CREATE TABLE L_YESNO_RESP (
	CODE BOOLEAN NULL,
	DESCRIPTION TEXT NULL)
DISTRIBUTE BY (CODE);
